version: '3.4'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
      network: host
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
